---
- name: install IBM tape driver
  hosts: vtl
  become: yes

  tasks:
  
        - name: Install RPMBUILD
          yum: 
                name: rpm-build
                state: present

        - name: copy file to remote host
          copy: 
                src: ./lin_tape-3.0.31-1.src.rpm
                dest: /tmp/lin_tape-3.0.31-1.src.rpm

        - name: Build the rpm 
          shell:  rpmbuild --rebuild /tmp/lin_tape-3.0.31-1.src.rpm

        - name: Install the built RPM
          yum: 
                name:  /root/rpmbuild/RPMS/x86_64/lin_tape-3.0.31-1.x86_64.rpm
                state: present

        - find:
                paths: /dev
                patterns: "IBMtape*"
          register: find_results

        - file:
                path: "{{ item['path'] }}"
                mode: a+rw
          with_items: "{{ find_results['files'] }}"
